name: CI Pipeline

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build ./...

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin v2.1.6
        env:
          GOPATH: $HOME/go
      
      - name: Add golangci-lint to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH
      
      - name: Run Makefile check target (format + lint)
        run: make check